name: Test and Push Docker Image to ECR and Update Lambda

on:
  push:
    branches:
      - main
env:
  DOC_DB_USER: ${{ secrets.DOC_DB_USER }}
  DOC_DB_PASS: ${{ secrets.DOC_DB_PASS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          architecture: 'x64'
      # DBを外につながないといけないのでいらない
      #- name: get python version
      #  run: python -V
      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install pymongo aws-lambda-powertools ddt
      #- name: unittest for python
      #  run: python app/lambda_function_test.py
      - name: run test on docker-compose
        run: |
          docker-compose up -d
          docker exec blog_python_lambda python lambda_function_test.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t blog_python_lambda:latest -f Dockerfile .

      - name: Tag Docker image for ECR
        run: |
          docker tag blog_python_lambda:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/blog_python_lambda:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/blog_python_lambda:latest

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
          --function-name blogLambdaFunction \
          --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/blog_python_lambda:latest
